cache:
  paths:
    - ccache/

kinetic_catkin_tests:
  image: ros:kinetic-robot
  stage: build
  before_script:
   - apt update >/dev/null && apt install -y git >/dev/null
   - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
   - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
   - apt-get install -y -qq libgtest-dev
   - (cd /usr/src/gtest; cmake . && make && cp *.a /usr/lib/)
  script:
    - catkin build romea_common --cmake-args -DBUILD_TESTS=ON
    - cd build/romea_common
    - GTEST_COLOR=1 ctest --output-on-failure


melodic_catkin_tests:
  image: ros:melodic-robot
  stage: build
  before_script:
   - apt update >/dev/null && apt install -y git >/dev/null
   - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
   - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
   - apt-get install -y -qq libgtest-dev
   - (cd /usr/src/gtest; cmake . && make && cp *.a /usr/lib/)
  script:
    - catkin build romea_common --cmake-args -DBUILD_TESTS=ON
    - catkin test romea_common

# noetic
noetic_catkin_build:
  image: ros:noetic-robot
  stage: test
  before_script:
   - apt update >/dev/null && apt install -y git >/dev/null
   - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
   - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
  script:
    - catkin build romea_common --cmake-args -DBUILD_TESTS=ON
    - catkin test romea_common
